import Head from 'next/head'
import styles from '../styles/Home.module.css'
import * as tf from '@tensorflow/tfjs';
import React from 'react';

export default function Home() {

  const model = tf.loadLayersModel("http://localhost:3000/facial_3_js/model.json").then(console.log("loaded"));


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://raw.githubusercontent.com/justadudewhohacks/face-api.js/master/dist/face-api.min.js" type="text/javascript"></script>
        <script src="https://cdn.jsdelivr.net/gh/wallat/compiled-opencvjs/v4.2.0/opencv.js" type="text/javascript"></script>
        
        <script src="script.js" type="text/javascript"></script>

      </Head>

      <body>
          <video id="videoInput"></video> 
          <canvas id="canvasOutput"></canvas>
          <button onClick={window['start']}>Start</button>
      </body>

    </div>
  )
}
